name: evaluation-pipeline
services:
  aggregate_eval_results:
    build:
      args: []
      context: components/aggregate_eval_results
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "evaluation-pipeline", "run_id":
      "evaluation-pipeline-20231128171812", "component_id": "aggregate_eval_results",
      "cache_key": "60ebd6a22412f70a815c2c4986f95f52"}'
    - --output_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/aggregate_eval_results/manifest.json
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "aggregate_eval_results", "description": "Component that aggregates
      results of the evaluation of the retriever", "image": "ghcr.io/ml6team/aggregate_eval_results:dev",
      "consumes": {"text": {"fields": {"context+precision": {"type": "float32"}, "context+relevancy":
      {"type": "float32"}}}}, "produces": {"text": {"fields": {"metric": {"type":
      "string"}, "score": {"type": "float32"}}}}}'
    - --input_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/retriever_eval/manifest.json
    depends_on:
      retriever_eval:
        condition: service_completed_successfully
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
    - /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/local_file:/data
  embed_text:
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "evaluation-pipeline", "run_id":
      "evaluation-pipeline-20231128171812", "component_id": "embed_text", "cache_key":
      "72e2bb18d4672ef8bfbce7f21cf5369f"}'
    - --output_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/embed_text/manifest.json
    - --model_provider
    - huggingface
    - --model
    - all-MiniLM-L6-v2
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "Embed text", "description": "Component that generates embeddings
      of text passages.", "image": "fndnt/embed_text:0.6.2", "consumes": {"text":
      {"fields": {"data": {"type": "string"}}}}, "produces": {"text": {"fields": {"data":
      {"type": "string"}, "embedding": {"type": "array", "items": {"type": "float32"}}}}},
      "args": {"model_provider": {"description": "The provider of the model - corresponding
      to langchain embedding classes. \nCurrently the following providers are supported:
      aleph_alpha, cohere, huggingface, openai, \nvertexai.\n", "type": "str", "default":
      "huggingface"}, "model": {"description": "The model to generate embeddings from.
      \nChoose an available model name to pass to the model provider''s langchain
      embedding class.\n", "type": "str", "default": "None"}, "api_keys": {"description":
      "The API keys to use for the model provider that are written to environment
      variables.\nPass only the keys required by the model provider or conveniently
      pass all keys you will ever need. \nPay attention how to name the dictionary
      keys so that they can be used by the model provider.\n", "type": "dict", "default":
      {}}, "auth_kwargs": {"description": "Additional keyword arguments required for
      api initialization/authentication.\n", "type": "dict", "default": {}}}}'
    - --input_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/load_from_csv_file/manifest.json
    depends_on:
      load_from_csv_file:
        condition: service_completed_successfully
    image: fndnt/embed_text:0.6.2
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
    - /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/local_file:/data
  load_from_csv_file:
    build:
      args: []
      context: components/load_from_csv
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "evaluation-pipeline", "run_id":
      "evaluation-pipeline-20231128171812", "component_id": "load_from_csv_file",
      "cache_key": "db7d55d0b8a27bab11a6f077e3d444ea"}'
    - --output_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/load_from_csv_file/manifest.json
    - --dataset_uri
    - /data/wikitext_1000_q.csv
    - --column_separator
    - ;
    - --column_name_mapping
    - '{"question": "text_data"}'
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "Load from csv file", "description": "Component that loads a dataset
      from a csv file", "image": "ghcr.io/ml6team/load_from_csv:dev", "produces":
      {"text": {"fields": {"data": {"type": "string"}}}}, "args": {"dataset_uri":
      {"description": "The remote path to the parquet file/folder containing the dataset",
      "type": "str"}, "column_separator": {"description": "Define the column separator
      of the csv file", "type": "str"}, "column_name_mapping": {"description": "Mapping
      of the consumed dataset", "type": "dict", "default": {}}, "n_rows_to_load":
      {"description": "Optional argument that defines the number of rows to load.
      Useful for testing pipeline runs on a small scale", "type": "int", "default":
      "None"}, "index_column": {"description": "Column to set index to in the load
      component, if not specified a default globally unique index will be set", "type":
      "str", "default": "None"}}}'
    depends_on: {}
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
    - /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/local_file:/data
  retrieve_from_weaviate:
    build:
      args: []
      context: components/retrieve_from_weaviate
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "evaluation-pipeline", "run_id":
      "evaluation-pipeline-20231128171812", "component_id": "retrieve_from_weaviate",
      "cache_key": "0731294a120b9d81025fb0f64dcac7f7"}'
    - --output_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/retrieve_from_weaviate/manifest.json
    - --weaviate_url
    - http://host.docker.internal:8080
    - --class_name
    - Index
    - --top_k
    - '2'
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "retrieve_from_weaviate", "description": "Component that retrieves
      chunks from a weaviate vectorDB", "image": "ghcr.io/ml6team/retrieve_from_weaviate:dev",
      "consumes": {"text": {"fields": {"data": {"type": "string"}, "embedding": {"type":
      "array", "items": {"type": "float32"}}}}}, "produces": {"text": {"fields": {"data":
      {"type": "string"}, "retrieved+chunks": {"type": "array", "items": {"type":
      "string"}}}}}, "args": {"weaviate_url": {"description": "The URL of the weaviate
      instance.", "type": "str", "default": "http://localhost:8080"}, "class_name":
      {"description": "The name of the weaviate class that will be created and used
      to store the embeddings. Should follow the weaviate naming conventions.", "type":
      "str"}, "top_k": {"description": "Number of chunks to retrieve", "type": "int"}}}'
    - --input_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/embed_text/manifest.json
    depends_on:
      embed_text:
        condition: service_completed_successfully
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
    - /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/local_file:/data
  retriever_eval:
    build:
      args: []
      context: components/retriever_eval
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "evaluation-pipeline", "run_id":
      "evaluation-pipeline-20231128171812", "component_id": "retriever_eval", "cache_key":
      "a5836c7b5212ece05c4b4fe9de47bfa0"}'
    - --output_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/retriever_eval/manifest.json
    - --openai_key
    - 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
    - --metrics
    - '["context_precision", "context_relevancy"]'
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "retriever_eval", "description": "Component that evaluates the retriever
      using RAGAS", "image": "ghcr.io/ml6team/retriever_eval:dev", "consumes": {"text":
      {"fields": {"data": {"type": "string"}, "retrieved+chunks": {"type": "array",
      "items": {"type": "string"}}}}}, "produces": {"text": {"fields": {"question":
      {"type": "string"}, "contexts": {"type": "array", "items": {"type": "string"}},
      "context+precision": {"type": "float32"}, "context+relevancy": {"type": "float32"}}}},
      "args": {"openai_key": {"description": "OpenAI key", "type": "str"}, "metrics":
      {"description": "RAGAS metrics to compute", "type": "list", "items": {"type":
      "str"}}}}'
    - --input_manifest_path
    - /data-dir/evaluation-pipeline/evaluation-pipeline-20231128171812/retrieve_from_weaviate/manifest.json
    depends_on:
      retrieve_from_weaviate:
        condition: service_completed_successfully
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
    - /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/local_file:/data
version: '3.8'
