name: ingestion-pipeline-li
services:
  create_nodes:
    build:
      args: []
      context: components/li_create_nodes
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "ingestion-pipeline-li", "run_id":
      "ingestion-pipeline-li-20231113165000", "component_id": "create_nodes", "cache_key":
      "a5837c4809bdbe11397cd0ae3ddfe69f"}'
    - --output_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/create_nodes/manifest.json
    - --chunk_size
    - '512'
    - --chunk_overlap
    - '50'
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "create_nodes", "description": "Create and store LlamaIndex Nodes",
      "image": "hakimovich99/li_create_nodes:dev", "consumes": {"text": {"fields":
      {"data": {"type": "string"}}}}, "produces": {"text": {"fields": {"original+document+id":
      {"type": "string"}, "chunk": {"type": "string"}, "node": {"type": "string"}}}},
      "args": {"chunk_size": {"description": "chunks size", "type": "int"}, "chunk_overlap":
      {"description": "chunks overlapping", "type": "int"}}}'
    - --input_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/load_from_huggingface_hub/manifest.json
    depends_on:
      load_from_huggingface_hub:
        condition: service_completed_successfully
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
  get_embeddings:
    build:
      args: []
      context: components/li_get_embeddings
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "ingestion-pipeline-li", "run_id":
      "ingestion-pipeline-li-20231113165000", "component_id": "get_embeddings", "cache_key":
      "7f7f001e95a278e738cf13ae49f448eb"}'
    - --output_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/get_embeddings/manifest.json
    - --hf_embed_model
    - BAAI/bge-small-en
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "get_embeddings", "description": "Component that embeds text", "image":
      "hakimovich99/li_get_embeddings:dev", "consumes": {"text": {"fields": {"original+document+id":
      {"type": "string"}, "chunk": {"type": "string"}, "node": {"type": "string"}}}},
      "produces": {"text": {"fields": {"original+document+id": {"type": "string"},
      "chunk": {"type": "string"}, "node": {"type": "string"}}}}, "args": {"hf_embed_model":
      {"description": "name of the chosen embedding model", "type": "str"}}}'
    - --input_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/create_nodes/manifest.json
    depends_on:
      create_nodes:
        condition: service_completed_successfully
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
  load_from_huggingface_hub:
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "ingestion-pipeline-li", "run_id":
      "ingestion-pipeline-li-20231113165000", "component_id": "load_from_huggingface_hub",
      "cache_key": "d49c56a1b1b95a767dcdaa4852a222f9"}'
    - --output_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/load_from_huggingface_hub/manifest.json
    - --dataset_name
    - wikitext@~parquet
    - --column_name_mapping
    - '{"text": "text_data"}'
    - --n_rows_to_load
    - '10'
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "Load from huggingface hub", "description": "Component that loads
      a dataset from huggingface hub", "image": "fndnt/load_from_hf_hub:0.6.2", "produces":
      {"text": {"fields": {"data": {"type": "string"}}}}, "args": {"dataset_name":
      {"description": "Name of dataset on the hub", "type": "str"}, "column_name_mapping":
      {"description": "Mapping of the consumed hub dataset to fondant column names",
      "type": "dict", "default": {}}, "image_column_names": {"description": "Optional
      argument, a list containing the original image column names in case the dataset
      on the hub contains them. Used to format the image from HF hub format to a byte
      string.", "type": "list", "default": []}, "n_rows_to_load": {"description":
      "Optional argument that defines the number of rows to load. Useful for testing
      pipeline runs on a small scale", "type": "int", "default": "None"}, "index_column":
      {"description": "Column to set index to in the load component, if not specified
      a default globally unique index will be set", "type": "str", "default": "None"}}}'
    depends_on: {}
    image: fndnt/load_from_hf_hub:0.6.2
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
  write_to_vector_db:
    build:
      args: []
      context: components/li_write_to_vector_db
    command:
    - --metadata
    - '{"base_path": "/data-dir", "pipeline_name": "ingestion-pipeline-li", "run_id":
      "ingestion-pipeline-li-20231113165000", "component_id": "write_to_vector_db",
      "cache_key": "a12defca2ebf6626a0ac3f5aaa4566b9"}'
    - --output_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/write_to_vector_db/manifest.json
    - --local_url
    - http://host.docker.internal:8080
    - --index_name
    - Llama_Paper
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --component_spec
    - '{"name": "write_to_vector_db", "description": "Component that adds nodes to
      a Weaviate vectorDB", "image": "hakimovich99/li_write_to_vector_db:dev", "consumes":
      {"text": {"fields": {"node": {"type": "string"}}}}, "args": {"cloud_store":
      {"description": "set to True if weaviate cloud storage", "type": "bool", "default":
      false}, "wcs_username": {"description": "username of cloud cluster account",
      "default": "None", "type": "str"}, "wcs_password": {"description": "password
      of cloud cluster account", "default": "None", "type": "str"}, "wcs_url": {"description":
      "url of cloud cluster account", "default": "None", "type": "str"}, "local_url":
      {"description": "local host url", "default": "None", "type": "str"}, "index_name":
      {"description": "index of the stored data", "default": "None", "type": "str"}}}'
    - --input_manifest_path
    - /data-dir/ingestion-pipeline-li/ingestion-pipeline-li-20231113165000/get_embeddings/manifest.json
    depends_on:
      get_embeddings:
        condition: service_completed_successfully
    ports:
    - 8787:8787
    volumes:
    - source: /Users/hakimamri/Documents/GitHub/fondant-usecase-RAG/src/data-dir
      target: /data-dir
      type: bind
version: '3.8'
